# Helper functions
eval "$(cat ~/.local/share/shelper.sh 2>/dev/null || curl -s suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export SERVER=$(ref SERVER 127.0.0.1)
export CA=$(ref CA $SERVER:11443)
export DOMAIN=$(ref DOMAIN 'localhost')
export IMAP=$(ref IMAP imap.$DOMAIN)
export SMTP=$(ref SMTP smtp.$DOMAIN)
export PASSWORDS=$(echo $PASSWORDS | base64 -d)
export USERS=$(ref USERS "$(keyval :all $PASSWORDS)")
