#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Start the service
chown -R data:data /app /tmp
runas data "sabnzbdplus --config-file /app/var --server :8080 &"

# Tail the logs and keep the container alive
sleep 5
tail -F /app/var/logs/*.log
