#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export DOMAIN=$(ref DOMAIN 'localhost')
deref /app/padlock/.env

# Start the node server
cd /app/padlock && git pull && npm start
