<?php
$AUTOCONFIG = array(
  'trusted_domains' => array ( 0 => '$SUBDOMAIN' ),
  "directory"     => "/data/owncloud",
  "dbtype"        => "mysql",
  "dbname"        => "$DATABASE",
  "dbuser"        => "root",
  "dbpass"        => "",
  "dbhost"        => "$SERVER",
  "dbtableprefix" => "oc_",
  "dbdriveroptions" => array(
    PDO::MYSQL_ATTR_SSL_CA   => "/app/certs/ca.crt",
    PDO::MYSQL_ATTR_SSL_CERT => "/app/certs/$NAME.crt",
    PDO::MYSQL_ATTR_SSL_KEY  => "/app/certs/$NAME.key",
  ),
  "adminlogin"    => "$USER",
  "adminpass"     => "$PASS",
  'memcache.local' => '\OC\Memcache\APCu',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'loglevel' => 3,
  'maintenance' => false,
  'log_type' => 'owncloud',
  'logtimezone' => 'UTC',
  'log_rotate_size' => 104857600,
);
