#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export SERVER=$(ref SERVER 127.0.0.1)
export DB=$(ref DB $SERVER:3306)
export CA=$(ref CA $SERVER:11443)
export DOMAIN=$(ref DOMAIN 'localhost')
export NAME=$(ref NAME root@mariadb.$DOMAIN)
export USER=$(ref USER $(key :first $PASSWORDS))
export PASS=$(ref PASS $(val :first $PASSWORDS))
export SUBDOMAIN=$(ref SUBDOMAIN owncloud.$DOMAIN)
export DATABASE=owncloud

# Wait for Padlock to be running
waitfor $CA

# Download certificate
copy $CA/$NAME.key /app/certs/$NAME.key
copy $CA/$NAME.crt /app/certs/$NAME.crt
copy $CA/ca.crt /app/certs/ca.crt

# Wait for MariaDB to be running
waitfor $DB /app/certs/$NAME

# Start redis
service redis-server start

# Prepare OwnCloud
cp /app/autoconfig.php /app/var/autoconfig.php
deref /app/var/autoconfig.php
cp -f /app/owncloud/config.dist/* /app/var

# Start the service
service apache2 start

# Tail the logs and keep the container alive
tail -F /var/log/apache2/error.log
