#!/bin/bash
source ~/.bashrc

# Wait for Padlock to be running
waitfor $CA

# Download certificate
copy $CA/$NAME.key /app/certs/$NAME.key
copy $CA/$NAME.crt /app/certs/$NAME.crt
copy $CA/ca.crt /app/certs/ca.crt

# Prepare OwnCloud var directory
mkdir -p /app/var/config /app/var/apps /app/var/themes
rm -f /app/owncloud/config && ln -sf /app/var/config /app/owncloud/config
rm -f /app/owncloud/apps   && ln -sf /app/var/apps   /app/owncloud/apps
rm -f /app/owncloud/themes && ln -sf /app/var/themes /app/owncloud/themes

# Make sure no files are missing from the download 
for dir in config apps themes; do
  for path in /app/owncloud.dist/${dir}/*; do 
    rm -rf /app/var/${dir}/$(basename $path)
    cp -r $path /app/var/${dir}/$(basename $path)
  done
done

# Copy and deref autoconfig
cp -f /app/autoconfig.php /app/var/config/autoconfig.php
deref /app/var/config/autoconfig.php

# Fix permissions
chown -R data:data /app/owncloud /app/var /tmp
chmod -R 775 /app/var && chmod -R -x+X /app/var

# Wait for MariaDB to be running
waitfor $DB /app/certs/$NAME

# Start the service
service apache2 start

# Start up cron
cron

# Tail the logs and keep the container alive
tail -F /var/log/apache2/error.log /data/owncloud/owncloud.log
