#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Start the service
chown -R data:data /app/var
runas data "/usr/bin/btsync --config /app/btsync.conf"

# Tail the logs and keep the container alive
tail -F /app/var/sync.log
