#!/bin/bash
source ~/.bashrc

# Start the service
chown -R data:data /app/var
runas data "/usr/bin/btsync --config /app/btsync.conf"

# Tail the logs and keep the container alive
tail -F /app/var/sync.log
