#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
DOMAIN=$(ref DOMAIN localhost)
SERVER=$(ref SERVER 127.0.0.1)
GATEWAY=$(ref GATEWAY 192.168.1.1)
CA=$(ref CA 127.0.0.1)

# Find all proxy files and run proxify
for f in $(find /app/var -maxdepth 2 -name "*.proxy"); do
  cd /app && proxify $f
done

# nginx configuration
cat /app/nginx.*.conf >> /app/nginx.sites.conf
cat /app/var/nginx/nginx.*.conf >> /app/nginx.sites.conf
deref /app/nginx.sites.conf

# dnsmasq configuration
cat /app/dnsmasq.*.conf >> /app/dnsmasq.sites.conf
cat /app/var/dnsmasq/dnsmasq.*.conf >> /app/dnsmasq.sites.conf
deref /app/dnsmasq.sites.conf

# Run dnsimple scripts
cat /app/dnsimple.*.sh >> /app/dnsimple.sh
deref /app/dnsimple.sh
chmod a+x /app/dnsimple.sh
/app/dnsimple.sh

# Start the service
deref /app/nginx.conf
nginx -p /app -c /app/nginx.conf

# Start up dnsmasq
deref /app/dnsmasq.conf
dnsmasq --conf-file=/app/dnsmasq.conf

# Watch the log and keep the container alive
mkdir -p /var/log/nginx && touch /var/log/dnsmasq.log
tail -F /var/log/nginx/* -F /var/log/dnsmasq.log
