# Helper functions
eval "$(cat ~/.local/share/shelper.sh 2>/dev/null || curl -s suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export SERVER=$(ref SERVER 127.0.0.1)
export DB=$(ref DB $SERVER:3306)
export CA=$(ref CA $SERVER:11443)
export NAME=$(ref NAME root@mariadb.$DOMAIN)
