#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export LOGIN=$(ref LOGIN 'root:')
export DB_USER=${LOGIN%%:*}
export DB_PASS=${LOGIN##*:}
export DB_HOST=$(ref SERVER '127.0.0.1')
deref /app/homemaker/.env

# Start the node server
cd /app/homemaker && git pull && npm run server
