# Helper functions
eval "$(cat ~/.local/share/shelper.sh 2>/dev/null || curl -s suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export CA=$(ref CA $SERVER:11443)
export NAME=$(ref NAME mariadb.$DOMAIN)
export PASSWORDS=$(echo $PASSWORDS | base64 -d)
export USER=$(ref USER $(key :first $PASSWORDS))
export PASS=$(ref PASS $(val :first $PASSWORDS))
