#!/bin/bash
source ~/.bashrc

# Wait for CA to be available
waitfor $CA

# Download CRL from CA and restart server
copy $CA/ca.crl.pem /app/certs/ca.crl
service mysql restart

# Update log
echo "$(date) - updated CRL and reloaded mariadb" >> /app/log/mariadb.reload.log
