#!/bin/bash

# Backup all data
mysqldump --single-transaction --routines --triggers --all-databases > /app/var/dump.sql

# Update log
echo "$(date) - exported all data to /app/var/dump.sql" >> /app/log/mariadb.dump.log
