#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export CA=$(ref CA $SERVER:11443)
export NAME=$(ref NAME mariadb.$DOMAIN)
export USER=$(ref USER $(key :first $PASSWORDS))
export PASS=$(ref PASS $(val :first $PASSWORDS))
deref /app/my.cnf

# Link files to where they're expected
ln -f /app/my.cnf /etc/mysql/my.cnf
ln -f /app/mysqldump /etc/cron.daily/mysqldump

# Save the CA's certificate and CRL
msg "Save the CA's certificate and CRL"
copy $CA/ca.crt /app/certs/ca.crt
copy $CA/ca.crl.pem /app/certs/ca.crl

# Save the database's key & crt
msg "Save the database's key & crt"
copy $CA/$NAME.key /app/certs/$NAME.key
copy $CA/$NAME.crt /app/certs/$NAME.crt

# Ensure /app/var/mysql has content
mkdir -p /app/var/mysql
defined "$(ls -A /app/var/mysql)" || cp -r /var/lib/mysql/* /app/var/mysql

# Ensure mysql owns /app/certs & /app/var/mysql
chown -R mysql /app/certs
chown -R mysql /app/var/mysql
chown root /app/var/mysql/debian*.flag

# Cleanup previous sockets
rm -f /run/mysqld/mysqld.sock

# Start MariaDB
msg "Start MariaDB, wait 5 seconds..."
service mysql start
sleep 5

# Create the debian system maintence user (password is auto generated)
msg "Create the debian system maintence user (password is auto generated)"
MAINT_PASS=$(cat /etc/mysql/debian.cnf | grep -m 1 "password\s*=\s*"| sed 's/^password\s*=\s*//')
mysql -u root <<-EOF
    GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '$MAINT_PASS';
EOF

# Create the password user (from $USER:$PASS)
msg "Create the password user (from $USER:$PASS)"
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = '$USER';
    GRANT ALL PRIVILEGES ON *.* TO '$USER'@'localhost' IDENTIFIED BY '$PASS';
    GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%' IDENTIFIED BY '$PASS';
    FLUSH PRIVILEGES;
EOF

# Create the root user (requires client crt/key)
msg "Create the root user (requires client crt/key)"
ISSUER=$(curl $CA/ca.sub)
SUBJECT=$(curl $CA/root@$NAME.sub)
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = 'root' AND host = '%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' 
    REQUIRE SUBJECT '$SUBJECT'
    AND ISSUER '$ISSUER';
    FLUSH PRIVILEGES;
EOF

# Tail the logs and keep the container alive
tail -F /var/log/mysql.log
