#!/bin/bash
source ~/.bashrc

# Set configuration
deref /app/my.cnf

# Copy config where it is expected
ln -f /app/my.cnf /etc/mysql/my.cnf

# Ensure directories exist
mkdir -p /app/log
touch /app/log/mariadb.log

# Wait for Padlock to be running
waitfor $CA

# Save the CA's certificate and CRL
msg "Save the CA's certificate and CRL"
copy $CA/ca.crt /app/certs/ca.crt
copy $CA/ca.crl.pem /app/certs/ca.crl

# Save the database's key & crt
msg "Save the database's key & crt"
copy $CA/$NAME.key /app/certs/$NAME.key
copy $CA/$NAME.crt /app/certs/$NAME.crt

# Ensure /app/var/mysql has content
mkdir -p /app/var/mysql
defined "$(ls -A /app/var/mysql)" || cp -r /var/lib/mysql/* /app/var/mysql

# Ensure mysql owns /app/certs & /app/var/mysql
chown -R mysql /app/certs
chown -R mysql /app/var/mysql
chown -R mysql /app/log
chown root /app/var/mysql/debian*.flag

# Cleanup previous sockets
rm -f /run/mysqld/mysqld.sock

# Start MariaDB
msg "Start MariaDB, wait 5 seconds..."
service mysql start
sleep 5

# Flush hosts to unblock connections, allow more attempts
msg "Flush hosts to unblock connections"
mysql -u root <<-EOF
    FLUSH HOSTS;
    SET GLOBAL max_connect_errors=250000;
EOF

# Create the debian system maintence user (password is auto generated)
msg "Create the debian system maintence user (password is auto generated)"
MAINT_PASS=$(cat /etc/mysql/debian.cnf | grep -m 1 "password\s*=\s*"| sed 's/^password\s*=\s*//')
mysql -u root <<-EOF
    GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '$MAINT_PASS';
EOF

# Create the password user (from $USER)
msg "Create the password user (from $USER)"
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = '$USER';
    GRANT ALL PRIVILEGES ON *.* TO '$USER'@'localhost' IDENTIFIED BY '$PASS';
    GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%' IDENTIFIED BY '$PASS';
    FLUSH PRIVILEGES;
EOF

# Create the root user (requires client crt/key)
msg "Create the root user (requires client crt/key)"
subject() {
  local sub=$(grep Subject: $1)
  sub=${sub//Subject: /\/}
  echo ${sub//, /\/}
}
ISSUER=$(curl -s $CA/ca.txt | subject)
SUBJECT=$(curl -s $CA/root@$NAME.txt | subject)
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = 'root' AND host = '%';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' 
    REQUIRE SUBJECT '$SUBJECT'
    AND ISSUER '$ISSUER';
    FLUSH PRIVILEGES;
EOF

# Start up cron
cron

# Tail the logs and keep the container alive
tail -F /app/log/*.log
