#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export CA=$(ref CA '127.0.0.1')
export DOMAIN=$(ref DOMAIN localhost)
export LOGIN=$(ref LOGIN 'user:pass')
export NAME=${LOGIN%%:*}
export PASS=${LOGIN##*:}
deref /app/my.cnf

# Directory for SSL
mkdir -p /app/certs

# Save the CA's certificate and CRL
curl $CA/ca.crt > /app/certs/ca.crt
curl $CA/ca.crl.pem > /app/certs/ca.crl

# Save the database's key & crt
curl $CA/mariadb.${DOMAIN}.key > /app/certs/mariadb.${DOMAIN}.key
curl $CA/mariadb.${DOMAIN}.crt > /app/certs/mariadb.${DOMAIN}.crt

# Ensure /app/var/mysql has content
mkdir -p /app/var/mysql
defined "$(ls -A /app/var/mysql)" || cp -r /var/lib/mysql/* /app/var/mysql

# Ensure mysql owns /app/certs & /app/var/mysql
chown -R mysql /app/certs
chown -R mysql /app/var/mysql
chown root /app/var/mysql/debian*.flag

# Cleanup previous sockets
rm -f /run/mysqld/mysqld.sock

# Start MariaDB
/usr/sbin/mysqld                               \
  --ssl-ca=/app/certs/ca.crt                   \
  --ssl-capath=/app/certs                      \
  --ssl-crl=/app/certs/ca.crl                  \
  --ssl-cert=/app/certs/mariadb.${DOMAIN}.crt  \
  --ssl-key=/app/certs/mariadb.${DOMAIN}.key   \
  --ssl-cipher=DHE-RSA-AES256-SHA

# Create the debian system maintence user (password is auto generated)
MAINT_PASS=$(cat /etc/mysql/debian.cnf | grep -m 1 "password\s*=\s*"| sed 's/^password\s*=\s*//')
mysql -u root <<-EOF
    GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '$MAINT_PASS';
EOF

# Create the password user (from $LOGIN)
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = '$NAME';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON *.* TO '$NAME'@'localhost' IDENTIFIED BY '$PASS';
    GRANT ALL PRIVILEGES ON *.* TO '$NAME'@'%' IDENTIFIED BY '$PASS';
EOF

# Create the root user (requires client cert)
ISSUER=$(curl $CA/ca.sub)
SUBJECT=$(curl $CA/root@mariadb.sub)
mysql -u root <<-EOF
    DELETE FROM mysql.user WHERE user = 'root' AND host = '%';
    FLUSH PRIVILEGES;
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' 
    REQUIRE SUBJECT '$SUBJECT'
    AND ISSUER '$ISSUER' 
    AND CIPHER 'DHE-RSA-AES256-SHA';
EOF

# Tail the logs and keep the container alive
tail -F /var/log/mysql.log
