#!/bin/bash
source ~/.bashrc

# Create client config directories for static IP assignment
rm -rf /app/tun.ccd/* /app/tap.ccd/*
while read line; do
  db=$(echo $line | sed 's/ \{1,\}/,/g')
  echo "ifconfig-push ${TUN}.$(key :2 $db) 255.255.255.0" > /app/tun.ccd/$(key :1 $db)@${NAME}
  echo "ifconfig-push ${TAP}.$(key :3 $db) 255.255.255.0" > /app/tap.ccd/$(key :1 $db)@${NAME}
done < /app/dhcp

# Activate forwarding
append "net.ipv4.ip_forward=1" /etc/sysctl.conf

# Wait for Padlock to be running
msg "Ensure $CA is running"
waitfor $CA

# Download CA certificate
copy $CA/ca.crt /app/ca.crt

# Download OVPN profile prepended with tun/tap.conf
curl $CA/$NAME.tun.ovpn | cat /app/tun.conf - > /app/$NAME.tun.ovpn
curl $CA/$NAME.tap.ovpn | cat /app/tap.conf - > /app/$NAME.tap.ovpn
chmod 600 /app/*.ovpn

# Expand any variables
deref /app/$NAME.tun.ovpn
deref /app/$NAME.tap.ovpn
deref /app/verify
deref /app/tun
deref /app/tap

# Start openvpn and tail the log
cd /app && touch tun.log tap.log
while true; do openvpn /app/$NAME.tun.ovpn; done >> /app/tun.log &
while true; do openvpn /app/$NAME.tap.ovpn; done >> /app/tap.log &
tail -F /app/*.log
