#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
USER=data
OUTPUT=/app
DOMAIN=$(ref DOMAIN localhost)
SERVER=$(ref SERVER 127.0.0.1)
GATEWAY=$(ref GATEWAY 192.168.1.1)
CA=$(ref CA 127.0.0.1)
LOGIN=$(ref LOGIN "$USER:$USER")
DNSIMPLE=$(ref DNSIMPLE '')

# Find all proxify files and run proxify. Creates:
# - /app/nginx.conf
# - /app/*.nginx.conf
# - /app/dnsmasq.conf
# - /app/*.dnsmasq.conf
# - /app/*.dnsimple.sh
# - /app/htpasswd
# - /app/ca.crt
# - /app/ca.crl
# - /app/ca.pem
# - /app/*.key
# - /app/*.pem
for f in $(find /app/var -maxdepth 2 -name "*.proxify"); do
  cd /app && proxify $f
done

# nginx configuration
rm -rf /app/000.nginx.conf
cat /app/var/nginx/*.nginx.conf >> /app/000.nginx.conf
deref /app/000.nginx.conf

# dnsmasq configuration
rm -rf /app/000.dnsmasq.conf
cat /app/var/dnsmasq/*.dnsmasq.conf >> /app/000.dnsmasq.conf
deref /app/000.dnsmasq.conf

# Run dnsimple scripts
rm -rf /app/dnsimple.conf
cat /app/*.dnsimple.sh >> /app/dnsimple.sh
chmod a+x /app/dnsimple.sh
/app/dnsimple.sh

# Start up nginx and dnsmasq
nginx -p /app -c /app/nginx.conf
dnsmasq --conf-file=/app/dnsmasq.conf

# Watch the log and keep the container alive
tail -F /app/*.log
