#!/bin/bash
source ~/.bashrc

# Wait for Padlock to be running
waitfor $CA

# Find all proxify files and run proxify. Creates:
# - /app/start.sh
# - /app/nginx.conf
# - /app/nginx/*.nginx.conf
# - /app/htpasswd/*.htpasswd
# - /app/dnsmasq.conf
# - /app/dnsmasq/*.dnsmasq.conf
# - /app/dns.sh
# - /app/dns/*.sh
# - /app/certs/ca.crt
# - /app/certs/ca.crl
# - /app/certs/*.pem
cd /app/proxify && git pull
for FILE in $(find /app/var -maxdepth 2 -name "*.proxify"); do
  cd /app && proxify $FILE
done

# Ensure directories exist
directories="/app/nginx /app/dnsmasq /app/dns /app/certs /app/log /app/error"
mkdir -p $directories

# additional nginx, dnsmasq configuration
for CONF in nginx dnsmasq; do
  for FILE in $(find /app/var -maxdepth 2 -name "*.${CONF}.conf"); do
    rm -rf /app/${CONF}/000.${CONF}.conf
    cat $FILE >> /app/${CONF}/000.${CONF}.conf
    deref /app/${CONF}/000.${CONF}.conf
  done
done

# Ensure proper permissions
chown -R $USER $directories
chgrp -R $USER $directories

# Run dnsimple scripts, start nginx & dnsmasq
mv /app/dns.sh /app/dns.disabled.sh # remove this
/app/start.sh

# Update the CRL and reload nginx every hour
msg "Update the CRL and reload nginx every hour"
while true; do 
  sleep 1h && waitfor $CA
  copy $CA/ca.crl.pem /app/certs/ca.crl
  service nginx reload
  echo "$(date) - updated CRL and reloaded nginx"
done >> /app/log/nginx.reload.log &

# Watch the log and keep the container alive
tail -F /app/log/*.log
