#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export USER=data
export OUTPUT=/app
export DOMAIN=$(ref DOMAIN localhost)
export SERVER=$(ref SERVER 127.0.0.1)
export CA=$(ref CA $SERVER:11443)
export PASSWORDS=$(ref PASSWORDS "$USER:$USER")
export DNSIMPLE=$(ref DNSIMPLE '')

# Find all proxify files and run proxify. Creates:
# - /app/start.sh
# - /app/nginx.conf
# - /app/nginx/*.nginx.conf
# - /app/htpasswd/*.htpasswd
# - /app/dnsmasq.conf
# - /app/dnsmasq/*.dnsmasq.conf
# - /app/dnsimple.sh
# - /app/dnsimple/*.dnsimple.sh
# - /app/certs/ca.crt
# - /app/certs/ca.crl
# - /app/certs/*.pem
cd /app/proxify && git pull
for FILE in $(find /app/var -maxdepth 2 -name "*.proxify"); do
  cd /app && proxify $FILE
done

# Ensure directories exist
directories="/app/nginx /app/dnsmasq /app/dnsimple /app/certs /app/log /app/error"
mkdir -p $directories

# additional nginx, dnsmasq configuration
for CONF in nginx dnsmasq; do
  rm -rf /app/${CONF}/000.${CONF}.conf
  cat /app/var/${CONF}/*.${CONF}.conf >> /app/${CONF}/000.${CONF}.conf
  deref /app/${CONF}/000.${CONF}.conf
done

# Ensure proper permissions
chown -R $USER $directories
chgrp -R $USER $directories

# Run dnsimple scripts, start nginx & dnsmasq
/app/start.sh

# Watch the log and keep the container alive
tail -F /app/log/*.log
