production:
  adapter: mysql2
  encoding: utf8
  database: $DATABASE
  pool: 5
  timeout: 5000
  host: $SERVER
  username: root
  sslkey: /app/certs/$NAME.key
  sslcert: /app/certs/$NAME.crt
  sslca: /app/certs/ca.crt

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
