#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export SERVER=$(ref SERVER 127.0.0.1)
export DB=$(ref DB $SERVER:3306)
export CA=$(ref CA $SERVER:11443)
export NAME=$(ref NAME root@mariadb.$DOMAIN)
export DATABASE=kandan
deref /app/kandan/config/database.yml

# Wait for Padlock to be running
waitfor $CA

# Download certificate
copy $CA/$NAME.key /app/certs/$NAME.key
copy $CA/$NAME.crt /app/certs/$NAME.crt
copy $CA/ca.crt /app/certs/ca.crt

# Wait for MariaDB to be running
waitfor $DB /app/certs/$NAME

# Prepare the app
export RAILS_ENV=production
cd /app/kandan && git pull 
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake kandan:bootstrap

# Mounted volume is public system directory
ln -sf /app/var /app/kandan/public/system

# Start the app
bundle exec rails server thin -p 6100 -e production
