#!/bin/bash
eval "$(cat ~/.local/share/shelper.sh || curl suderman.github.io/shelper/shelper.sh)"

# Set environment variables
export LOGIN=$(ref LOGIN 'root:')
export DB_USER=${LOGIN%%:*}
export DB_PASS=${LOGIN##*:}
export DB_HOST=$(ref SERVER '127.0.0.1')
export DB_NAME=kandan
export RAILS_ENV=production
deref /app/kandan/config/database.yml

# Prepare the app
cd /app/kandan && git pull 
bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake assets:precompile
bundle exec rake kandan:bootstrap

# Start the app
bundle exec rails server thin -p 6100 -e production
